name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'   # cada hora automáticamente
  push:
    branches: [main]       # también al hacer commit
  workflow_dispatch:        # permite correrlo manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Update GitHub Stats Card
        uses: anuraghazra/github-readme-stats@latest
        with:
          username: MORENOG-2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update Streak Stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          user: MORENOG-2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit updated README
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "⚡ Stats actualizadas automáticamente"
          git push
